steps:

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    for d in */; do 
      config="${d}cloudbuild.yaml"
      if [[ ! -f "${config}" ]]; then
        for ff in $d/*; do
        config1="${ff}/cloudbuild.yaml"
        if [[ ! -f "${config1}" ]]; then
        continue
        fi
        echo "Building $ff ... "
      (
        gcloud builds submit $ff --config=${config1}
      ) &
        done
      fi
      echo "Building $d ... "
      (
        gcloud builds submit $d --config=${config}
      ) &
    done
    wait
