steps:

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    find */ -type f -name cloudbuild* -print0 | while read -d $'\0' file; do
    gcloud builds submit --config=$file
    done
