steps:

- name: node:10.15.1
  entrypoint: npm
  args: ['version','patch'] # please mention major/minor/patch
  dir: 'repo2'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "hiiiiiiiiiiiiiiiiiii"
    echo "this is repo2222222222222 folder"
  dir: 'repo2'
